# Generated by Django 5.2.6 on 2026-01-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory')),
            ],
        ),
    ]
