# Generated by Django 5.2.6 on 2026-03-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contactus_feedback_payment_address_cart_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Qty',
            field=models.IntegerField(default=1),
        ),
    ]
