# Generated by Django 5.2.6 on 2026-03-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='comments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='pincode',
            new_name='Pincode',
        ),
    ]
