# Generated by Django 5.2.6 on 2026-03-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_address_address_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='Type',
        ),
    ]
