# Generated by Django 5.2.6 on 2026-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_date_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
